apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-app-values
  namespace: giantswarm
data:
  configmap-values.yaml: |
    configmap:
      use-forwarded-headers: "false"
{{- if eq .Provider "aws" }}
      use-proxy-protocol: "true"
{{- end }}
    controller:
      enableSSLChainCompletion: true
      service:
        type: NodePort
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: nginx-ingress-controller-app
  name: nginx-ingress-controller-app
  namespace: giantswarm
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: nginx-ingress-controller-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "nginx-ingress-controller-app-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 2.12.1
